### ISSUE TITLE
 Bug? Unable to get Pages to show added page

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#1833]
### Steps to Reproduce

1. Install PSU 3.6.2 MSI on Windows 10 device
2. Navigate to Dashboards and create a dashboard
   - Name: Debug-Dashboard
   - URL: debug-dashboard
4. Click edit details for Debug-Dashboard
5. Drop down the Pages menu on the right sidebar and click new page
6. Create new page called debugpage
7. Navigate to new page via url e.g. http://127.0.0.1:5000/admin/dashboards/3/pages/1

### Expected behavior

```console
Page should be visible and not return an error when you manually navigate
```

### Actual behavior

```console
the files create in the c:\ProgramData\UniversalAutomation location however they are not visible on the front end

When you attempt to navigate manually you receive the error:


TypeError: o.content is undefined


f@http://127.0.0.1:5000/admin/static/js/21.b504347b.chunk.js:1:49501
d@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:389232
p@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:389572
main
p<@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:911815
h/</<@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:911648
section
v<@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:912052
h/</<@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:911648
n@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:3110027
Suspense
u@http://127.0.0.1:5000/admin/static/js/main.fc4e3f69.chunk.js:1:63547
div
div
b<@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:3389419
G@http://127.0.0.1:5000/admin/static/js/21.b504347b.chunk.js:1:51615
n@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:3110027
Suspense
u@http://127.0.0.1:5000/admin/static/js/main.fc4e3f69.chunk.js:1:63547
m@http://127.0.0.1:5000/admin/static/js/main.fc4e3f69.chunk.js:1:100781
g@http://127.0.0.1:5000/admin/static/js/main.fc4e3f69.chunk.js:1:100959
1463/r.default@http://127.0.0.1:5000/admin/static/js/21.b504347b.chunk.js:1:57815
d@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:389232
p@http://127.0.0.1:5000/admin/static/js/17.88fed178.chunk.js:2:389572
h
```

### Environment data

PowerShell Universal 3.6.2
Windows 10

Debug log Generation occurred after 0923 on 16/12/2022

### Visuals

[logs.2022-12-16.zip](https://github.com/ironmansoftware/issues/files/10244545/logs.2022-12-16.zip)
![2022-12-16 09_26_41-Window](https://user-images.githubusercontent.com/106333485/208069185-c44b6ba2-00fc-41b7-bb09-07fdaeacf453.png)
![2022-12-16 09_25_33-Window](https://user-images.githubusercontent.com/106333485/208069190-1d9376b9-e56c-4f86-9cce-d08c67347543.png)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/bug-unable-to-get-pages-to-show-added-page/8288/7

**Comment by adamdriscoll** [comment]
Thanks for the logs! That helped. Can you please try this nightly build: 3713819987? https://ironmansoftware.com/release/powershell-universal-nightly It contains a fix that should resolve this.

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll,

I installed 3713819987 and rebooted, however, this did not resolve the problem.

**Comment by MattHarrisUltima** [comment]
Attaching new logs replicating the problem under build 3713819987.
[logs.2022-12-16(1).zip](https://github.com/ironmansoftware/issues/files/10247180/logs.2022-12-16.1.zip)

**Comment by adamdriscoll** [comment]
Bummer. Thanks for giving it and shot and the logs.

**Comment by MattHarrisUltima** [comment]
Never a problem :)

**Comment by Omzig** [comment]
> Thanks for the logs! That helped. Can you please try this nightly build: 3713819987? https://ironmansoftware.com/release/powershell-universal-nightly It contains a fix that should resolve this.

I am having trouble getting it installed/started :(

```
Application '/LM/W3SVC/5/ROOT/psuSandbox' with physical root 'E:\src\psu\psuSandbox\' failed to start process with commandline '".\Universal.Server.exe" --appsettings E:\src\psu\appsettings.psuSandbox.json' with multiple retries. Failed to bind to port '3177'. First 30KB characters of captured stdout and stderr logs from multiple retries:

Application '/LM/W3SVC/5/ROOT/psuSandbox' with physical root 'E:\src\psu\psuSandbox\' failed to start process with commandline '".\Universal.Server.exe" --appsettings E:\src\psu\appsettings.psuSandbox.json' at stage 'CreateProcessW', ErrorCode = '0x80070002', assigned port 3177, retryCounter '0'.

Application '/LM/W3SVC/5/ROOT/psuSandbox' with physical root 'E:\src\psu\psuSandbox\' failed to start process with commandline '".\Universal.Server.exe" --appsettings E:\src\psu\appsettings.psuSandbox.json' at stage 'CreateProcessW', ErrorCode = '0x80070002', assigned port 17867, retryCounter '1'.
```

**Comment by Omzig** [comment]
its not working for me

**Comment by adamdriscoll** [comment]
@Omzig @MattHarrisUltima  - Are either of you up for a screen share around this? I haven't been able to reproduce this on any of my labs so would love to poke around a bit.

**Comment by Omzig** [comment]
> re either of you up for a screen share around this? I haven't been able to reproduce this on any of my labs so would love to poke around a bit.

@adamdriscoll, I totally am.

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll,

Apologies for the radio silence i have been on annual leave.

I am around today (UK time) and then back on Jan 4th

**Comment by MikeShepard** [comment]
This is working for me with the 3.6.3 nightly build from 12/27
