### ISSUE TITLE
$EventData for New-UDDatePicker provides output in multiple formats

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2835]
### Version

4.0.12

### Severity

High

### Steps to Reproduce

I have tested this in 2 code bocks (with and without the -Format parameter):

```
New-UDDatePicker -Id 'managecompanysecretexpirydate' -Format 'dd/MM/yyyy' -OnChange {
        $session:ChangedDate = $Eventdata
    Sync-UDElement -id dynamicbox
}

New-UDDynamic -id dynamicbox -Content {
    New-UDParagraph -Text $session:ChangedDate
}
```

```
New-UDDatePicker -Id 'managecompanysecretexpirydate' -OnChange {
        $session:ChangedDate = $Eventdata
    Sync-UDElement -id dynamicbox
}

New-UDDynamic -id dynamicbox -Content {
    New-UDParagraph -Text $session:ChangedDate
}
```

### Expected behavior

```console
$EventData should present data in the same format
```

### Actual behavior

```console
The output passed to $EventData is presented in at least 1 of 2 formats.

E.g.

11/10/2023 14:47:11
"2023-11-10T14:47:11+00:00"
```
Please see screenshots for examples
```


### Additional Environment data

PSU container image: ironmansoftware/universal:4.0.12-modules

### Visuals

![2023-11-09 14_45_19-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/453d08c3-bda9-4f36-a6f4-4cfcee6d0657)
![2023-11-09 14_45_09-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/d9ef2d69-0f82-4f28-b0e6-172d0ee8ba2c)
![2023-11-09 14_44_36-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/5383a723-8732-463c-8b1f-6e709a784f93)
![2023-11-09 14_47_29-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/60de4cfd-b28f-479e-ae46-01eecf4f8c59)
![2023-11-09 14_47_22-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/03def459-221f-488d-8238-11f0bd85a2fb)

**Comment by adamdriscoll** [comment]
This was fixed in 4.1.6.

#2716

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll ,

I am still getting this bug in 4.2.6. Can you take another look?

```
New-UDDatePicker -Id "managecompanysecretexpirydate" -TimeZone 'GMT' -OnChange {
   $Session:EnvironmentConnectivityExpiryDate = $EventData
   $Session:EnvironmentConnectivityExpiryDate > EnvironmentConnectivityExpiryDate.txt
}
```

![2023-12-18 13_29_50-EnvironmentConnectivityExpiryDate txt - Notepad](https://github.com/ironmansoftware/issues/assets/106333485/d05b5987-7c62-4ebd-84a9-67498370a8ae)
![2023-12-18 13_29_10-EnvironmentConnectivityExpiryDate txt - Notepad](https://github.com/ironmansoftware/issues/assets/106333485/2a8c45df-2668-44f2-8781-e6a1d832efb7)
