### ISSUE TITLE
Missing data labels or data values in pie charts using UDChartJS and UDNivoChart

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3293]
### Version

4.2.18

### Severity

Low

### Environment

msi

### Steps to Reproduce

New-UDApp -Title 'PowerShell Universal' -Content {
    $Data = 1..5 | ForEach-Object { 
        $value = Get-Random -Max 100
        [PSCustomObject]@{
            Name  = "DataLabel$value"
            Id    = "DataLabel$value"
            Label = "DataLabel$value"
            Value = $value
            Color = "#$((1..6 | ForEach-Object{ '{0:X}' -f (Get-Random -Max 16) }) -join '')"
        }
    }

    New-UDNivoChart -Id 'testPie' -Pie -Data $Data -Colors @{datum = 'data.color' } -Responsive

    New-UDChartJS -Type pie -Data $Data -LabelProperty Name -DataProperty Value -Options @{
        aspectRatio = 3
        plugins     = @{
            legend = @{
                display = $true
            }
        }
    } -BackgroundColor $Data.Color
}

### Expected behavior

```console
Show the labels and values as described in the screenshot attached.
```

### Actual behavior

```console
Not showing the labes and the values, screenshot attached.  pie chart presentation for our dashboard app. It's required to display both data label and data value. I tried both New-UDNivoChart and New-UDChartJS but couldn't make it to show both, either missing label or value.
```

### Additional Environment data

Documentation sample not showing this setting. 

### Screenshots/Animations

![Screenshot 2024-04-25 213158](https://github.com/ironmansoftware/issues/assets/68939160/75f9c541-8a0a-4fdd-b371-85018f6afb6a)

**Comment by timoline** [comment]
just curious....is it fixed in 4.2.20?

**Comment by JCrabtree911** [comment]
I have just installed 4.2.21 and can confirm that this is still not working as expected.
