### ISSUE TITLE
Using admin rights in such an issue

### ISSUE THREAD

**Issue by oliwex** [ironmansoftware/powershell-universal#3524]
### Summary of the new feature / enhancement

Product: PowerShell Universal
Version: 1.4.6
Hi, to be honest i am compleetly amateur realted to Universal Dashboard. I just find it on Internet and think that it is good piece of software so i use it free version to test.

I installed it on my local computer and create normal static website with static data and it works.
But now i want to do something better.
Now i create website where I have grid, and every element of grid is a stylized card. In thet card i have list of items, so this is a snipped of code of that list:

$body = New-UDCardBody -Content {
                    New-UDList -Children {
                        New-UDListItem -Label 'sdfsfdfds' -Icon (New-UDIcon -Icon user -Size 1x) -SubTitle $(quser /server:Computer
                        New-UDListItem -Label 'IP' -Icon (New-UDIcon -Icon laptop -Size 1x) -SubTitle $(Invoke-Command Computer {ipconfig}
                    }
                }
The problem is when i execute it, asking about that data on my local computer that works, but if i ask remote computer about data(which require admin rights) then i have access denied. I have almost 200 remote computer, on every computer i have admin rights, and everytime i have access denied.
Thet code executed on terminal Windows 11 works fine but in dashboard i have an error: “Access denied”. So to the question:

How to configure such an issue to make it works right ? I ask also about configuring it on admin panel and configure in code. (But if it can be configured only in code i prefer this way).
Or maybe it is neccesary to configure in windows , if yes please provide step by step images how to do this.

### Proposed technical implementation details (optional)

Show more code use cases related to that issue

**Comment by Omzig** [comment]
1) your powershell is missing some )
- fixed 
```powershell
$body = New-UDCardBody -Content {
    New-UDList -Children {
        New-UDListItem -Label 'sdfsfdfds' -Icon (New-UDIcon -Icon user -Size 1x) -SubTitle $(quser /server:Computer)
        New-UDListItem -Label 'IP' -Icon (New-UDIcon -Icon laptop -Size 1x) -SubTitle $(Invoke-Command Computer {ipconfig})
    }
}
```
2) did you setup powershell remoting? https://learn.microsoft.com/en-us/powershell/scripting/security/remoting/running-remote-commands?view=powershell-7.4
3) this would fit better in a forum post ;)  https://forums.ironmansoftware.com/c/powershell-universal/17

**Comment by oliwex** [comment]
@Omzig 
Ok. fixed.Changed nothing. Error still exist.
Yes i setup remoting, because i use it without UD functions -> in terminal and in ise and in VSC and works fine. The problem is with UD.
Posted in forum -> waiting for answer

**Comment by Omzig** [comment]
- https://forums.ironmansoftware.com/t/executing-script-with-admin-rights/11045/2?u=omzig

**Comment by adamdriscoll** [comment]
This really, really depends on how PSU is running. https://blog.ironmansoftware.com/script-differences/

**Comment by oliwex** [comment]
Ok,but where screens or code info how to do this?

**Comment by adamdriscoll** [comment]
If your local system account (what the service runs as by default) cannot access the remote machines, you need to set the service account user to one that has the privileges you are looking for. 

![image](https://github.com/user-attachments/assets/813cfbb0-b893-4746-98ce-a0d84486dca8)

**Comment by adamdriscoll** [comment]
I'm closing this as it is not a problem with the software and a configuration discussion that can continue on our forums.

**Comment by oliwex** [comment]
@adamdriscoll 
I think my english is not that perfect to understand you. Could you provide more step by step instructions with screens.
Also...Problem with accessing remote machines is only with UDDashboard. Normally...using ise i can do this by Invoke-Command or other cmdlets
