### ISSUE TITLE
Schedule properties has blank script value

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3669]
### Version

5.0.1

### Severity

High

### Environment

msi

### Steps to Reproduce

1. Upgrade PSU to version 5.0.1 on a Windows Server 2022 Standard environment.
2. Open the properties of any existing schedule that is configured using a CRON trigger.
3. Observe that the script value appears blank in the schedule properties.
4. If the schedule is saved without modifying the blank script value, the schedule is deleted.
5. Check the schedules.ps1 file; notice that the reference to the script is removed, making the schedule invalid and causing it to no longer be listed in the UI.

### Expected behavior

```console
The script value should be correctly displayed in the schedule properties, allowing users to view and modify the schedule without it being deleted.
```

### Actual behavior

```console
The script value appears blank in the schedule properties. If the schedule is saved with the blank script value, the schedule is deleted, and the reference to the script is removed from the schedules.ps1 file, causing the schedule to be invalid and no longer listed in the UI.
```

**Comment by adamdriscoll** [comment]
This was fixed in 5.0.2. The user should upgrade to at least 5.0.4 because of the security issue.

**Comment by bt-ndollimount** [comment]
Hi @adamdriscoll ,

This issue appears to be still present in 5.0.5.

![image](https://github.com/user-attachments/assets/dc759e31-0e32-4cae-8428-e27212e509ef)
![image](https://github.com/user-attachments/assets/4666694a-b1a9-4736-98e3-9af9bca815a4)

Thanks,
Nick Dollimount

**Comment by bt-ndollimount** [comment]
@adamdriscoll Should also note that when you manually select the script from the list and set the parameters (if needed) and save the changes, the schedules.ps1 is updated with the script file but it's missing the folder. This appears to break the schedule from actually running, which makes sense since the path is incorrect.

![image](https://github.com/user-attachments/assets/d525a704-7450-4735-a9ae-b0a44e3096a1)

You can see in the screenshot that the one that I updated, it had the Telemetry\ removed from the path.

**Comment by adamdriscoll** [comment]
This should be resolved in 5.0.6. We had a pretty serious performance problem that caused the blank script page and the full path is now the selection in the drop down.
