### ISSUE TITLE
Weird behaviour when sending a PSCustomObject with PSCredentials from a Dashboard to a PSUScript using Invoke-PSUScript

### ISSUE THREAD

**Issue by chauberg** [ironmansoftware/powershell-universal#4317]
### Description of Issue

I have a dashboard where I define a settings variable which is a PSCustomObject with some PSCredential variables inside, this is used in the dashboard for some function calls and then sent to a PSUScript using Invoke-PSUScript - the issue I'm having is that this works correctly sometimes (usually after a Dashboard restart) and then randomly fails, it seems like the types get wonky randomly.

I made the following test setup to replicate the issue:
**Dashboard**
```
function CallScript
{
    param ([PSCustomObject]$Settings)

    $scriptParameters = @{
        Settings = $Settings
    }
    Invoke-PSUScript -Script (Get-PSUScript -Name "TestCred.ps1") @scriptParameters | Tee-Object -Variable job | Wait-PSUJob
    $result = Get-PSUJobPipelineOutput -Job $job
    Write-Host $result
}

New-UDApp -Content {
    [PSCustomObject]$test = @{
        TestCredential = $Secret:PsCredentialTest
    }

    New-UDForm -Id "Form" -Content {} -OnSubmit {
        CallScript -Settings $test
    }
}
```

**TestCred.ps1**
```
param (
    [Parameter(Mandatory)]
    [PSCustomObject]
    [ValidateScript({
        function Validate
        {
            param (
                [Parameter(Mandatory)]
                [PSCredential]
                $TestCredential
            )
            return $true
        }
        $settings = $_
        Validate @settings
    })]
    $Settings
    )

Write-Host ($Settings | ConvertTo-Json)
```

I use a ValidateScript parameter in the script to ensure that the credential is passed properly.

As I type this I've clicked the submit button in the dashboard a couple of times where it has randomly succeeded the validation and also failed without me changing anything in the dashboard or the script.

![Image](https://github.com/user-attachments/assets/2b38ba5d-3489-4c03-ac3b-0a7a5907af8f)

I'm at a loss here, please help :D 

### Version

5.2.1

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

**Comment by chauberg** [comment]
Note that I am actually using a hashtable, not a PSCustomObject as the latter doesn't seem to play nice with splatting but it doesn't change the underlying issue, it seems that often the PSCredentials are delivered as a different type "System.Management.Automation.PSObject" instead of PSCredential which bricks the validation.. I made a function that iterates over my hashtable and casts properties to PSCredential inside the PSUScript before passing it into the function with validation as a hacky solution.

**Comment by adamdriscoll** [comment]
I cannot reproduce this in the 5.4 version. I have tried your sample (thanks so much for that) and I'm not seeing it any longer. There is a good chance it has been resolved by some change we have made.

**Comment by chauberg** [comment]
I'm still seeing this issue in 5.6.7, I use this function to mitigate the issue if that helps:

```
function Traverse {
    param (
        [Parameter(Mandatory)]
        [hashtable]$InputHashTable
    )
    $keys = $InputHashTable.Keys | ForEach-Object { $_ }
    foreach ($key in $keys) {
        $value = $InputHashTable[$key]
        Write-Debug "[$($key)] ($($value.GetType().FullName))"
        Write-Debug ($value| ConvertTo-Json -Depth 10)
        if ($value -is [Hashtable])
        {
            Write-Debug "Expanding.."
            $InputHashTable[$key] = (Traverse $value)
        }
        if ($value -isnot [PSCredential] -and $value -isnot [string] -and ($key -like "*Credential" -or $key -eq "Credential"))
        {
            Write-Debug "Casting '$key' with value of type: $($value.GetType().FullName) to PSCredential"
            $InputHashTable[$key] = [PSCredential]$value
        }
        Write-Debug " -- "
    }
    return $InputHashTable
}
$DebugPreference = 'Continue'
$Settings = (Traverse $Settings)
```
