### ISSUE TITLE
PSU Visual Studio Code Extension writes file changes to .universal folder as new file

### ISSUE THREAD

**Issue by JessePeden** [ironmansoftware/powershell-universal#4475]
### Description of Issue

When editing an existing script in PSU through the VS Code extension, saving the changes to the script causes the extension to create a new script file in the `.universal` folder rather update the existing script fie in whatever the correct path actually is.  The new file has the proper filename, but because it's not updating the existing script in the correct path, you end up with 2 copies of the script - one old (original) and one new (modified).  The new script also does not appear to get added to the scripts.ps1 file, so it's otherwise unusable as it can't be selected in the PSU interface outside of the Settings/Files area.

### Version

PSU: 5.3.3; VS Code Extension: 5.2.0

### Severity

High

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

### Features

VS Code Extension

**Comment by adamdriscoll** [comment]
I'm 99.8% sure this was fixed in 5.4 but I will try tomorrow. I don't see release notes on it so it could have been a dream.

**Comment by JessePeden** [comment]
@adamdriscoll Sounds good.  I tagged the other bug on here ( #4161 ) that looked like it was an identical issue.  Looks like that issue was closed as completed, but that user said it was still present in the current release of the VS Code extension as well.

**Comment by JessePeden** [comment]
> I'm 99.8% sure this was fixed in 5.4 but I will try tomorrow. I don't see release notes on it so it could have been a dream.

I just updated the extension to 5.4.0 and the issue still exists.  PSU is still on 5.3.3, in case that somehow matters.

**Comment by adamdriscoll** [comment]
This appears to be a server problem because using 5.4.0 does not present this issue.

**Comment by JessePeden** [comment]
~~Oh.  So you've already found the issue and fixed it for 5.4.1?~~

**Comment by adamdriscoll** [comment]
It is working in 5.4.0. The server needs to be that version though. The problem must have been in the server and not the extension.

**Comment by JessePeden** [comment]
> It is working in 5.4.0. The server needs to be that version though. The problem must have been in the server and not the extension.

My bad.  IDK why I thought you said it was still present in 5.4.0.  What's interesting is that we have another user that's editing his scripts with the extension and is NOT running into this issue.
