### ISSUE TITLE
Windows Authentication don't show logged in user

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#449]
When you don't have the Windows Authentication activated you can see what user that are logged in PSU in the right corner of the menubar as you know.

But if you have Windows Authentication you can't see the username.
I do understand that the logout button in the dropdown should bee disabled for Windows Authentication but it would bee great if you can see what user your logged in with.

**Comment by adamdriscoll** [comment]
This is a visual bug and has been resolved in 2.3.

**Comment by rwidmark** [comment]
> This is a visual bug and has been resolved in 2.3.

I did just try it and for me I still don't see the username of the logged in user.
