### ISSUE TITLE
5.6.12 - Logs folder are created in /root/.PowershellUniversal

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#5471]
### Description of Issue

In 5.6.12 the Logs folder are created in the /root/.PowershellUniversal folder for the Ubuntu 20.04 docker image.

<img width="488" height="154" alt="Image" src="https://github.com/user-attachments/assets/a759ca81-9889-4f77-a732-9c2da6cae85a" />

That means that new containers starting up, wont sync with Git:

<img width="1934" height="374" alt="Image" src="https://github.com/user-attachments/assets/887fa0e1-cf63-4794-9c81-addf865b0ecb" />

It should be stored under: /home/Universal

### Version

5.6.12

### Severity

Medium

### Hosting Method

Docker Container

### Operating System

Linux

### Database

PostgreSQL

### Licensed

Yes

### Additional Environment data

The config was configured using a configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: psu-config
  namespace: psu
data:
  TZ: "Europe/Copenhagen"
  Plugins__0: "PostgreSQL"
  Data__ConnectionString: "redacted-connection-string"
  Data__RepositoryPath: "/root/.PowerShellUniversal"
  Kestrel__Endpoints__HTTP__Url: "http://0.0.0.0:5000"
  DOTNET_USE_POLLING_FILE_WATCHER: "true"
```

**Comment by adamdriscoll** [comment]
@ksl28 The default config puts the repository in: /root/.PowerShellUniversal/Repository. If you either remove the Data__Repository env var or add /Repository it should fix this.

**Comment by ksl28** [comment]
> [@ksl28](https://github.com/ksl28) The default config puts the repository in: /root/.PowerShellUniversal/Repository. If you either remove the Data__Repository env var or add /Repository it should fix this.

@adamdriscoll - Thats a brainfart on me - your suggestion worked 👍 

As a debug i added `Logging__Path: "/home/Universal/Logs"`  but that didnt fix it - but the default settings, are just perfect.

Thanks for the reply 👍
