### ISSUE TITLE
Packager doesn't work with apostrophe 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#675]
The packager doesn't work when run from a path with an apostrophe or compiled from a path with an apostrophe

**Comment by PS1Online** [comment]
Hi Adam, I'm the user who reported this bug to you on 08/10/2021.
This problem still persists in the November release. Can it be fixed for the December release?
I have fixed the registry values so that the .ps1 scripts are executed with double click or with "Run with PowerShell" from any position without problem, even with paths with multiple consecutive spaces and with apostrophes. I also fixed the same problem when launching a PowerShell instance from a specific location:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.ps1]
@="Microsoft.PowerShellScript.1"

[HKEY_CLASSES_ROOT\Directory\Background\shell\Powershell\command]
@="\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -NoExit -Command \"Set-Location -LiteralPath \\\"%V\\.\\\"\""

[HKEY_CLASSES_ROOT\Directory\Shell\Powershell\command]
@="\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -NoExit -Command \"Set-Location -LiteralPath \\\"%V\\.\\\"\""

[HKEY_CLASSES_ROOT\Drive\shell\Powershell\command]
@="\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -NoExit -Command \"Set-Location -LiteralPath \\\"%V\\.\\\"\""

[HKEY_CLASSES_ROOT\Microsoft.PowerShellScript.1\DefaultIcon]
@="\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\",0"

[HKEY_CLASSES_ROOT\Microsoft.PowerShellScript.1\Shell\Open\Command]
@="\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -Command \"if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force }; & \\\"%1\\\"\""

[HKEY_CLASSES_ROOT\SystemFileAssociations\.ps1\Shell\0\Command]
@="\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -Command \"if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force }; & \\\"%1\\\"\""

[HKEY_CLASSES_ROOT\SystemFileAssociations\.ps1\Shell\Edit\Command]
@="\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe\" -File \"%1\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell]
"ExecutionPolicy"="RemoteSigned"

```

I hope these registry values can help you with your bugfixing operation.

**Comment by PS1Online** [comment]
> s

one or more apostrophes

**Comment by PS1Online** [comment]
> The packager doesn't work when run from a path with an apostrophe or compiled from a path with an apostrophe

one or more apostrophes.*

**Comment by PS1Online** [comment]
The download is still that of the November release, although the December release changelog has been provided.
Was this bug fixed in the December release?
The changelog does not report the bugfix for this issue.

**Comment by adamdriscoll** [comment]
This was resolved in the December release. It was a mistake on my part that it did not make it into the changelog.

**Comment by PS1Online** [comment]
The problem persists even in the December release.
What tests have you done to see that the problem has been solved?
I simply did the test that is present in the 2 attached images.

![error](https://user-images.githubusercontent.com/28962652/146408859-9233bc9d-127c-401d-aefc-bbc556201e54.png)
![success](https://user-images.githubusercontent.com/28962652/146408861-92c70e4a-9f9a-440a-bc4f-f25664123557.png)
