### ISSUE TITLE
UDTable unable to sort correctly by date

### ISSUE THREAD

**Issue by ZHumphries** [ironmansoftware/powershell-universal#9]
#### Description

I am trying to sort on a date column, but it New-UDTable appears to be sorting it as a string. I have confirmed the field being returned from SQL is a data time.

Note: This also occurs when using a PowerShell DateTime object

![image](https://user-images.githubusercontent.com/24667546/106893782-f17d5980-66e5-11eb-9e94-c7fee959c981.png)

Table Code
```
New-UDTable -Title 'IT Alerts' -Id 'ITAlerts' -Data $Data -Columns $Columns -PageSize 20 -Filter -Dense -Search -Export
```
Column Code
```
New-UDTableColumn -Property 'NotificationDate' -Title 'Notification Date' -IncludeInSearch -IncludeInExport -Sort
```

#### Additional Information

Discussed with psDevUK - https://forums.universaldashboard.io/t/new-udtable-column-sort-by-date/4408

Example code that demonstrates the problem

```
New-UDDashboard -Title 'DateSortTest' -Content {

    $Dates = @(
        '14/06/2021', '14/07/2021', '14/08/2021', '14/07/2020', '20/06/2021', '20/07/2021', '20/08/2021', '20/07/2020'
    )
    $TableData = @()
    $TableData += $Dates | ForEach-Object {
        [PSCustomObject]@{
            DateSortTest = Get-Date $_
        }
    }

    $Columns = @(
        New-UDTableColumn -Property 'DateSortTest' -Title 'DateSortTest'
    )
    New-UDTable -Title 'DateSortTest' -Id 'DateSortTest' -Data $TableData -Columns $Columns -PageSize 10

}
```

#### Version Information

- Universal: 1.5.9
- Universal Hosting Method: Executable
- PowerShell: 5.1 or 7.1
- Operating System: 2016

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This will be resolved in tonight's nightly build and release 1.5.15. We've added a new parameter to `New-UDTableColumn` to support sorting by datetime. 

```
    $Data = @(
        [PSCustomObject]@{ Name = (Get-Date).AddDays(10)}
        [PSCustomObject]@{ Name = (Get-Date).AddDays(1)}
        [PSCustomObject]@{ Name = (Get-Date).AddDays(6)}
        [PSCustomObject]@{ Name = (Get-Date).AddDays(3)}
    )

    $Columns = @(
        New-UDTableColumn -Property Name -SortType 'datetime'
    )

    New-UDTable -Id 'service_table' -Data $Data -ShowSort
```

**Comment by adamdriscoll** [comment]
Fixed in 1.5.15

**Comment by King-Louis-III** [comment]
This issue still isn't fixed using the provided example in 1.5.16

For one, the provided example doesn't call the $Columns, which I assume is a typo. Even if you do call it, the dates you are adding are going to sort properly regardless of sort type, as they will alphabetically sort in the same order.  Fixing the type and giving a better table like so:

```
$Data = @(
            [PSCustomObject]@{ Name = (Get-Date).AddDays(10)}
            [PSCustomObject]@{ Name = (Get-Date).AddDays(1)}
            [PSCustomObject]@{ Name = (Get-Date).AddDays(-363)}
            [PSCustomObject]@{ Name = (Get-Date).AddDays(6)}
            [PSCustomObject]@{ Name = (Get-Date).AddDays(3)}
        )
    
        $Columns = @(
            New-UDTableColumn -Property Name -SortType 'datetime'
        )
    
        New-UDTable -Id 'service_table' -Data $Data -ShowSort -Columns $Columns
```
        
  Results in the following:
  
![image](https://user-images.githubusercontent.com/60182200/118141399-51675880-b3d7-11eb-9ff5-e9d1f092ab20.png)

@adamdriscoll
